model_path: model/bert-base-japanese-v3_cross-encoder/final

train_doc_master: data/mmarco_ja_4_splade_distil/train/doc_master.ndjson
train_query_master: data/mmarco_ja_4_splade_distil/train/query_master.ndjson
validation_doc_master: data/mmarco_ja_4_splade_distil/validation/doc_master.ndjson
validation_query_master: data/mmarco_ja_4_splade_distil/validation/query_master.ndjson

hard_negative_init_scores: data/mmarco_ja_4_splade_distil/hard-negatives-init-scores.ndjson.gz
hard_negative_cross_encoder_scores: data/mmarco_ja_4_splade_distil/hard-negatives-cross-encoder-scores.ndjson.gz

max_token_len: 256
char_per_token_ratio: 1.8
predict_batch_size: 128
