name: pre-commit
on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
  push:

defaults:
  run:
    working-directory: ./

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Takumi Guard
        uses: flatt-security/setup-takumi-guard-pypi@v1
        with:
          bot-id: "BT01KJVWWCWV4T141Y8XDTX6CH1G"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "./.python-version"

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files -c ./.pre-commit-config.yaml
